name: color_shade
description: Extends the Color class to generate shades from the primary color.
version: 1.0.0
homepage: https://github.com/fldnascimento/color_shade

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
